name: React app github deploy

on:
  push:
    branches:
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Construir la imagen de Docker
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mi-imagen:latest .

      # Paso 4: Subir la imagen al registro
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mi-imagen:latest